-- Legacy tables used by v2 pages
-- Run in Supabase SQL Editor (schema: public)

create table if not exists public.duanmian1 (
  "selectedNumber" integer generated by default as identity primary key,
  thickness integer,
  width integer,
  "isSelected" integer default 1
);

create table if not exists public.duanmian2 (
  num integer generated by default as identity primary key,
  "steelthicknessLow" varchar(45),
  "steelthicknessHigh" varchar(45),
  "thicknessLow" varchar(45),
  "thicknessHigh" varchar(45)
);

-- Optional: only create if you have this table in legacy MySQL.
create table if not exists public.slablengthstandard (
  num integer generated by default as identity primary key,
  "STD_MIN" varchar(45),
  "STD_MAX" varchar(45),
  "FULL_MIN" varchar(45),
  "FULL_MAX" varchar(45),
  "SHORT_MIN" varchar(45),
  "SHORT_MAX" varchar(45),
  "SLAB_THK_MIN" varchar(45),
  "SLAB_THK_MAX" varchar(45)
);

-- Helpful indexes for page reads
create index if not exists idx_duanmian1_selected on public.duanmian1 ("isSelected");
create index if not exists idx_duanmian2_num on public.duanmian2 (num);

